

----For esx items 

INSERT INTO `items` (`name`, `label`) VALUES

  ('strippedbass', 'strippedbass'),
  ('silverymonnow', 'silverymonnow'),
   ('goldentrout', 'goldentrout'),
   ('bluegill', 'bluegill'),
   ('tench', 'tench'),
   ('whitefish', 'whitefish'),
   ('crappie', 'crappie'),
   ('cruciancarp', 'cruciancarp'),
   ('bluebackherring', 'bluebackherring'),
   ('bulltrout', 'bulltrout'),
   ('laketrout', 'laketrout'),
   ('perch', 'perch'),
   ('chub', 'chub'),
   ('colorodopikeminnow', 'colorodopikeminnow'),
   ('drumfish', 'drumfish'),
   ('wallaye', 'wallaye'),
   ('americanshad', 'americanshad'),
   ('palidsturgeon', 'palidsturgeon'),
   ('pike', 'pike'),
   ('blackcrappie', 'blackcrappie'),
   ('bream', 'bream'),
   ('brooktrout', 'brooktrout'),
   ('shortnosesucker', 'shortnosesucker'),
   ('smallmouthbass', 'smallmouthbass'),
   ('arowana', 'arowana'),
   ('sweetfish', 'sweetfish'),
   ('whitebass', 'whitebass'),
   ('alabamasturgeon', 'alabamasturgeon'),
   ('lakesturgeon', 'lakesturgeon'),
   ('koicarpblack', 'koicarpblack'),   
   ('lahontancutthroattrout', 'lahontancutthroattrout'),
   ('spoonlurebait', 'spoonlurebait'),
   ('threesidedbait', 'threesidedbait'),
   ('tailfishbait', 'tailfishbait'),
   ('doublehookbait', 'doublehookbait'),
   ('triplehooksbait', 'triplehooksbait'),
   ('woodenrod', 'woodenrod'),
   ('slimmaterialrod', 'slimmaterialrod'),
   ('danishrod', 'danishrod'),
   ('koidrod', 'koidrod'),
   ('finewood', 'finewood');


--------------------------------------------------------------------------


--- For qb items 



['strippedbass'] = {
    ['name'] = 'strippedbass', 			 	  	  	
    ['label'] = 'strippedbass', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'strippedbass.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},

['silverymonnow'] = {
    ['name'] = 'silverymonnow', 			 	  	  	
    ['label'] = 'silverymonnow', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'silverymonnow.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['goldentrout'] = {
    ['name'] = 'goldentrout', 			 	  	  	
    ['label'] = 'goldentrout', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'goldentrout.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['bluegill'] = {
    ['name'] = 'bluegill', 			 	  	  	
    ['label'] = 'bluegill', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'bluegill.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['tench'] = {
    ['name'] = 'tench', 			 	  	  	
    ['label'] = 'tench', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'tench.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['whitefish'] = {
    ['name'] = 'whitefish', 			 	  	  	
    ['label'] = 'whitefish', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'whitefish.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['crappie'] = {
    ['name'] = 'crappie', 			 	  	  	
    ['label'] = 'crappie', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'crappie.png', 				
    ['unique'] = false, 	
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['cruciancarp'] = {
    ['name'] = 'cruciancarp', 			 	  	  	
    ['label'] = 'cruciancarp', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'cruciancarp.png', 				
    ['unique'] = false, 	
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['bluebackherring'] = {
    ['name'] = 'bluebackherring', 			 	  	  	
    ['label'] = 'bluebackherring', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'bluebackherring.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['bulltrout'] = {
    ['name'] = 'bulltrout', 			 	  	  	
    ['label'] = 'bulltrout', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'bulltrout.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['laketrout'] = {
    ['name'] = 'laketrout', 			 	  	  	
    ['label'] = 'laketrout', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'laketrout.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['perch'] = {
    ['name'] = 'perch', 			 	  	  	
    ['label'] = 'perch', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'perch.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['chub'] = {
    ['name'] = 'chub', 			 	  	  	
    ['label'] = 'chub', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'chub.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['colorodopikeminnow'] = {
    ['name'] = 'colorodopikeminnow', 			 	  	  	
    ['label'] = 'colorodopikeminnow', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'colorodopikeminnow.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['drumfish'] = {
    ['name'] = 'drumfish', 			 	  	  	
    ['label'] = 'drumfish', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'drumfish.png', 				
    ['unique'] = false, 	
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['wallaye'] = {
    ['name'] = 'wallaye', 			 	  	  	
    ['label'] = 'wallaye', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'wallaye.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['americanshad'] = {
    ['name'] = 'americanshad', 			 	  	  	
    ['label'] = 'americanshad', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'americanshad.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['palidsturgeon'] = {
    ['name'] = 'palidsturgeon', 			 	  	  	
    ['label'] = 'palidsturgeon', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'palidsturgeon.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['pike'] = {
    ['name'] = 'pike', 			 	  	  	
    ['label'] = 'pike', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'pike.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['blackcrappie'] = {
    ['name'] = 'blackcrappie', 			 	  	  	
    ['label'] = 'blackcrappie', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'blackcrappie.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['bream'] = {
    ['name'] = 'bream', 			 	  	  	
    ['label'] = 'bream', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'bream.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['brooktrout'] = {
    ['name'] = 'brooktrout', 			 	  	  	
    ['label'] = 'brooktrout', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'brooktrout.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['shortnosesucker'] = {
    ['name'] = 'shortnosesucker', 			 	  	  	
    ['label'] = 'shortnosesucker', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'shortnosesucker.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['smallmouthbass'] = {
    ['name'] = 'smallmouthbass', 			 	  	  	
    ['label'] = 'smallmouthbass', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'smallmouthbass.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['arowana'] = {
    ['name'] = 'arowana', 			 	  	  	
    ['label'] = 'arowana', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'arowana.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['sweetfish'] = {
    ['name'] = 'sweetfish', 			 	  	  	
    ['label'] = 'sweetfish', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'sweetfish.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['whitebass'] = {
    ['name'] = 'whitebass', 			 	  	  	
    ['label'] = 'whitebass', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'whitebass.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['alabamasturgeon'] = {
    ['name'] = 'alabamasturgeon', 			 	  	  	
    ['label'] = 'alabamasturgeon', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'alabamasturgeon.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['lakesturgeon'] = {
    ['name'] = 'lakesturgeon', 			 	  	  	
    ['label'] = 'lakesturgeon', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'lakesturgeon.png', 				
    ['unique'] = false, 	
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['koicarpblack'] = {
    ['name'] = 'koicarpblack', 			 	  	  	
    ['label'] = 'koicarpblack', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'koicarpblack.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['lahontancutthroattrout'] = {
    ['name'] = 'lahontancutthroattrout', 			 	  	  	
    ['label'] = 'lahontancutthroattrout', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'lahontancutthroattrout.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['spoonlurebait'] = {
    ['name'] = 'spoonlurebait', 			 	  	  	
    ['label'] = 'spoonlurebait', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'spoonlurebait.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['threesidedbait'] = {
    ['name'] = 'threesidedbait', 			 	  	  	
    ['label'] = 'threesidedbait', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'threesidedbait.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['tailfishbait'] = {
    ['name'] = 'tailfishbait', 			 	  	  	
    ['label'] = 'tailfishbait', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'tailfishbait.png', 				
    ['unique'] = false, 	
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['doublehookbait'] = {
    ['name'] = 'doublehookbait', 			 	  	  	
    ['label'] = 'doublehookbait', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'doublehookbait.png', 				
    ['unique'] = false, 	
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['triplehooksbait'] = {
    ['name'] = 'triplehooksbait', 			 	  	  	
    ['label'] = 'triplehooksbait', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'triplehooksbait.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['woodenrod'] = {
    ['name'] = 'woodenrod', 			 	  	  	
    ['label'] = 'woodenrod', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'woodenrod.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['slimmaterialrod'] = {
    ['name'] = 'slimmaterialrod', 			 	  	  	
    ['label'] = 'slimmaterialrod', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'slimmaterialrod.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['danishrod'] = {
    ['name'] = 'danishrod', 			 	  	  	
    ['label'] = 'danishrod', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'danishrod.png', 				
    ['unique'] = false, 			
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['koidrod'] = {
    ['name'] = 'koidrod', 			 	  	  	
    ['label'] = 'koidrod', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'koidrod.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},
['finewood'] = {
    ['name'] = 'finewood', 			 	  	  	
    ['label'] = 'finewood', 					
    ['weight'] = 0, 		
    ['type'] = 'item', 		
    ['image'] = 'finewood.png', 				
    ['unique'] = false, 		
    ['useable'] = true, 	
    ['shouldClose'] = false,   
    ['combinable'] = nil,   
    ['description'] = 'Description'
},